# coding: utf-8

"""
    \"Data Governance Center: REST API v2\"

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.json_form_data_impl import JsonFormDataImpl  # noqa: E501
from swagger_client.rest import ApiException


class TestJsonFormDataImpl(unittest.TestCase):
    """JsonFormDataImpl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJsonFormDataImpl(self):
        """Test JsonFormDataImpl"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.json_form_data_impl.JsonFormDataImpl()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
