# coding: utf-8

"""
    \"Data Governance Center: REST API v2\"

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.json_field import JsonField  # noqa: E501
from swagger_client.rest import ApiException


class TestJsonField(unittest.TestCase):
    """JsonField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJsonField(self):
        """Test JsonField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.json_field.JsonField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
