# coding: utf-8

"""
    \"Data Governance Center: REST API v2\"

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.xml_ns0_find_attribute_types_request import XmlNs0FindAttributeTypesRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestXmlNs0FindAttributeTypesRequest(unittest.TestCase):
    """XmlNs0FindAttributeTypesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testXmlNs0FindAttributeTypesRequest(self):
        """Test XmlNs0FindAttributeTypesRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.xml_ns0_find_attribute_types_request.XmlNs0FindAttributeTypesRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
