# coding: utf-8

"""
    \"Data Governance Center: REST API v2\"

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.attribute_types_api import AttributeTypesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAttributeTypesApi(unittest.TestCase):
    """AttributeTypesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.attribute_types_api.AttributeTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_resource_attribute_type_resource_add_attribute_type_post(self):
        """Test case for resource_attribute_type_resource_add_attribute_type_post

        Adds new attribute type.  # noqa: E501
        """
        pass

    def test_resource_attribute_type_resource_add_attribute_types_post(self):
        """Test case for resource_attribute_type_resource_add_attribute_types_post

        Adds multiple attribute types.  # noqa: E501
        """
        pass

    def test_resource_attribute_type_resource_change_attribute_type_patch(self):
        """Test case for resource_attribute_type_resource_change_attribute_type_patch

        Changes the attribute type with the information that is present in the request.  # noqa: E501
        """
        pass

    def test_resource_attribute_type_resource_change_attribute_types_patch(self):
        """Test case for resource_attribute_type_resource_change_attribute_types_patch

        Changes multiple attribute types.  # noqa: E501
        """
        pass

    def test_resource_attribute_type_resource_find_attribute_types_get(self):
        """Test case for resource_attribute_type_resource_find_attribute_types_get

        Returns attribute types matching the given search criteria.  # noqa: E501
        """
        pass

    def test_resource_attribute_type_resource_get_attribute_type_by_name_get(self):
        """Test case for resource_attribute_type_resource_get_attribute_type_by_name_get

        Returns attribute type identified by given name.  # noqa: E501
        """
        pass

    def test_resource_attribute_type_resource_get_attribute_type_get(self):
        """Test case for resource_attribute_type_resource_get_attribute_type_get

        Returns attribute type identified by given id.  # noqa: E501
        """
        pass

    def test_resource_attribute_type_resource_remove_attribute_type_delete(self):
        """Test case for resource_attribute_type_resource_remove_attribute_type_delete

        Removes attribute type identified by given id.  # noqa: E501
        """
        pass

    def test_resource_attribute_type_resource_remove_attribute_types_delete(self):
        """Test case for resource_attribute_type_resource_remove_attribute_types_delete

        Removes multiple attribute types.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
