# coding: utf-8

"""
    \"Data Governance Center: REST API v2\"

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.xml_ns0_asset_type_impl import XmlNs0AssetTypeImpl  # noqa: E501
from swagger_client.rest import ApiException


class TestXmlNs0AssetTypeImpl(unittest.TestCase):
    """XmlNs0AssetTypeImpl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testXmlNs0AssetTypeImpl(self):
        """Test XmlNs0AssetTypeImpl"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.xml_ns0_asset_type_impl.XmlNs0AssetTypeImpl()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
