# coding: utf-8

"""
    \"Data Governance Center: REST API v2\"

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.xml_ns0_single_value_list_attribute_impl import XmlNs0SingleValueListAttributeImpl  # noqa: E501
from swagger_client.rest import ApiException


class TestXmlNs0SingleValueListAttributeImpl(unittest.TestCase):
    """XmlNs0SingleValueListAttributeImpl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testXmlNs0SingleValueListAttributeImpl(self):
        """Test XmlNs0SingleValueListAttributeImpl"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.xml_ns0_single_value_list_attribute_impl.XmlNs0SingleValueListAttributeImpl()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
