# coding: utf-8

"""
    \"Data Governance Center: REST API v2\"

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.issues_api import IssuesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIssuesApi(unittest.TestCase):
    """IssuesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.issues_api.IssuesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_resource_issue_resource_add_issue_post(self):
        """Test case for resource_issue_resource_add_issue_post

        Add a new issue with the given parameters.  # noqa: E501
        """
        pass

    def test_resource_issue_resource_find_issues_get(self):
        """Test case for resource_issue_resource_find_issues_get

        Returns issues matching the given search criteria.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
