# coding: utf-8

"""
    \"Data Governance Center: REST API v2\"

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.json_add_complex_relation_type_request import JsonAddComplexRelationTypeRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestJsonAddComplexRelationTypeRequest(unittest.TestCase):
    """JsonAddComplexRelationTypeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJsonAddComplexRelationTypeRequest(self):
        """Test JsonAddComplexRelationTypeRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.json_add_complex_relation_type_request.JsonAddComplexRelationTypeRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
