# coding: utf-8

"""
    \"Data Governance Center: REST API v2\"

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.xml_ns0_export_xml_to_file_request import XmlNs0ExportXMLToFileRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestXmlNs0ExportXMLToFileRequest(unittest.TestCase):
    """XmlNs0ExportXMLToFileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testXmlNs0ExportXMLToFileRequest(self):
        """Test XmlNs0ExportXMLToFileRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.xml_ns0_export_xml_to_file_request.XmlNs0ExportXMLToFileRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
