# coding: utf-8

"""
    \"Data Governance Center: REST API v2\"

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.json_paged_request import JsonPagedRequest  # noqa: F401,E501
from swagger_client.models.json_sort_field_find_attributes_request import JsonSortFieldFindAttributesRequest  # noqa: F401,E501
from swagger_client.models.json_sort_order import JsonSortOrder  # noqa: F401,E501


class JsonFindAttributesRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'offset': 'float',
        'limit': 'float',
        'type_ids': 'list[str]',
        'asset_id': 'str',
        'sort_order': 'JsonSortOrder',
        'sort_field': 'JsonSortFieldFindAttributesRequest'
    }

    attribute_map = {
        'offset': 'offset',
        'limit': 'limit',
        'type_ids': 'typeIds',
        'asset_id': 'assetId',
        'sort_order': 'sortOrder',
        'sort_field': 'sortField'
    }

    def __init__(self, offset=None, limit=None, type_ids=None, asset_id=None, sort_order=None, sort_field=None):  # noqa: E501
        """JsonFindAttributesRequest - a model defined in Swagger"""  # noqa: E501

        self._offset = None
        self._limit = None
        self._type_ids = None
        self._asset_id = None
        self._sort_order = None
        self._sort_field = None
        self.discriminator = None

        if offset is not None:
            self.offset = offset
        if limit is not None:
            self.limit = limit
        if type_ids is not None:
            self.type_ids = type_ids
        if asset_id is not None:
            self.asset_id = asset_id
        if sort_order is not None:
            self.sort_order = sort_order
        if sort_field is not None:
            self.sort_field = sort_field

    @property
    def offset(self):
        """Gets the offset of this JsonFindAttributesRequest.  # noqa: E501

        The first result to retrieve. If not set (value = <tt>0</tt>), results will be retrieved starting from row <tt>0</tt>  # noqa: E501

        :return: The offset of this JsonFindAttributesRequest.  # noqa: E501
        :rtype: float
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this JsonFindAttributesRequest.

        The first result to retrieve. If not set (value = <tt>0</tt>), results will be retrieved starting from row <tt>0</tt>  # noqa: E501

        :param offset: The offset of this JsonFindAttributesRequest.  # noqa: E501
        :type: float
        """

        self._offset = offset

    @property
    def limit(self):
        """Gets the limit of this JsonFindAttributesRequest.  # noqa: E501

        The maximum number of results to retrieve. If not set (value = <tt>0</tt>), the default limit will be used  # noqa: E501

        :return: The limit of this JsonFindAttributesRequest.  # noqa: E501
        :rtype: float
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this JsonFindAttributesRequest.

        The maximum number of results to retrieve. If not set (value = <tt>0</tt>), the default limit will be used  # noqa: E501

        :param limit: The limit of this JsonFindAttributesRequest.  # noqa: E501
        :type: float
        """

        self._limit = limit

    @property
    def type_ids(self):
        """Gets the type_ids of this JsonFindAttributesRequest.  # noqa: E501

        The list of <code>id</code>s of the attribute types the found attributes should have  # noqa: E501

        :return: The type_ids of this JsonFindAttributesRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._type_ids

    @type_ids.setter
    def type_ids(self, type_ids):
        """Sets the type_ids of this JsonFindAttributesRequest.

        The list of <code>id</code>s of the attribute types the found attributes should have  # noqa: E501

        :param type_ids: The type_ids of this JsonFindAttributesRequest.  # noqa: E501
        :type: list[str]
        """

        self._type_ids = type_ids

    @property
    def asset_id(self):
        """Gets the asset_id of this JsonFindAttributesRequest.  # noqa: E501

        The <code>id</code> of the asset to find the attributes in  # noqa: E501

        :return: The asset_id of this JsonFindAttributesRequest.  # noqa: E501
        :rtype: str
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """Sets the asset_id of this JsonFindAttributesRequest.

        The <code>id</code> of the asset to find the attributes in  # noqa: E501

        :param asset_id: The asset_id of this JsonFindAttributesRequest.  # noqa: E501
        :type: str
        """

        self._asset_id = asset_id

    @property
    def sort_order(self):
        """Gets the sort_order of this JsonFindAttributesRequest.  # noqa: E501

        The sorting order  # noqa: E501

        :return: The sort_order of this JsonFindAttributesRequest.  # noqa: E501
        :rtype: JsonSortOrder
        """
        return self._sort_order

    @sort_order.setter
    def sort_order(self, sort_order):
        """Sets the sort_order of this JsonFindAttributesRequest.

        The sorting order  # noqa: E501

        :param sort_order: The sort_order of this JsonFindAttributesRequest.  # noqa: E501
        :type: JsonSortOrder
        """

        self._sort_order = sort_order

    @property
    def sort_field(self):
        """Gets the sort_field of this JsonFindAttributesRequest.  # noqa: E501

        The field on which the results are sorted  # noqa: E501

        :return: The sort_field of this JsonFindAttributesRequest.  # noqa: E501
        :rtype: JsonSortFieldFindAttributesRequest
        """
        return self._sort_field

    @sort_field.setter
    def sort_field(self, sort_field):
        """Sets the sort_field of this JsonFindAttributesRequest.

        The field on which the results are sorted  # noqa: E501

        :param sort_field: The sort_field of this JsonFindAttributesRequest.  # noqa: E501
        :type: JsonSortFieldFindAttributesRequest
        """

        self._sort_field = sort_field

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JsonFindAttributesRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
