# coding: utf-8

"""
    \"Data Governance Center: REST API v2\"

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.xml_ns0_gender import XmlNs0Gender  # noqa: F401,E501


class XmlNs0AddUserRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email_address': 'str',
        'first_name': 'str',
        'gender': 'XmlNs0Gender',
        'last_name': 'str',
        'user_name': 'str'
    }

    attribute_map = {
        'email_address': 'emailAddress',
        'first_name': 'firstName',
        'gender': 'gender',
        'last_name': 'lastName',
        'user_name': 'userName'
    }

    def __init__(self, email_address=None, first_name=None, gender=None, last_name=None, user_name=None):  # noqa: E501
        """XmlNs0AddUserRequest - a model defined in Swagger"""  # noqa: E501

        self._email_address = None
        self._first_name = None
        self._gender = None
        self._last_name = None
        self._user_name = None
        self.discriminator = None

        if email_address is not None:
            self.email_address = email_address
        if first_name is not None:
            self.first_name = first_name
        if gender is not None:
            self.gender = gender
        if last_name is not None:
            self.last_name = last_name
        if user_name is not None:
            self.user_name = user_name

    @property
    def email_address(self):
        """Gets the email_address of this XmlNs0AddUserRequest.  # noqa: E501

        The email address of the new user  # noqa: E501

        :return: The email_address of this XmlNs0AddUserRequest.  # noqa: E501
        :rtype: str
        """
        return self._email_address

    @email_address.setter
    def email_address(self, email_address):
        """Sets the email_address of this XmlNs0AddUserRequest.

        The email address of the new user  # noqa: E501

        :param email_address: The email_address of this XmlNs0AddUserRequest.  # noqa: E501
        :type: str
        """
        if email_address is not None and len(email_address) > 2147483647:
            raise ValueError("Invalid value for `email_address`, length must be less than or equal to `2147483647`")  # noqa: E501
        if email_address is not None and len(email_address) < 1:
            raise ValueError("Invalid value for `email_address`, length must be greater than or equal to `1`")  # noqa: E501

        self._email_address = email_address

    @property
    def first_name(self):
        """Gets the first_name of this XmlNs0AddUserRequest.  # noqa: E501

        The first name of the new user  # noqa: E501

        :return: The first_name of this XmlNs0AddUserRequest.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this XmlNs0AddUserRequest.

        The first name of the new user  # noqa: E501

        :param first_name: The first_name of this XmlNs0AddUserRequest.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def gender(self):
        """Gets the gender of this XmlNs0AddUserRequest.  # noqa: E501

        The gender of the user  # noqa: E501

        :return: The gender of this XmlNs0AddUserRequest.  # noqa: E501
        :rtype: XmlNs0Gender
        """
        return self._gender

    @gender.setter
    def gender(self, gender):
        """Sets the gender of this XmlNs0AddUserRequest.

        The gender of the user  # noqa: E501

        :param gender: The gender of this XmlNs0AddUserRequest.  # noqa: E501
        :type: XmlNs0Gender
        """

        self._gender = gender

    @property
    def last_name(self):
        """Gets the last_name of this XmlNs0AddUserRequest.  # noqa: E501

        The last name of the new user  # noqa: E501

        :return: The last_name of this XmlNs0AddUserRequest.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this XmlNs0AddUserRequest.

        The last name of the new user  # noqa: E501

        :param last_name: The last_name of this XmlNs0AddUserRequest.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def user_name(self):
        """Gets the user_name of this XmlNs0AddUserRequest.  # noqa: E501

        The name of the new user. Should be unique within all user names  # noqa: E501

        :return: The user_name of this XmlNs0AddUserRequest.  # noqa: E501
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this XmlNs0AddUserRequest.

        The name of the new user. Should be unique within all user names  # noqa: E501

        :param user_name: The user_name of this XmlNs0AddUserRequest.  # noqa: E501
        :type: str
        """
        if user_name is not None and len(user_name) > 2147483647:
            raise ValueError("Invalid value for `user_name`, length must be less than or equal to `2147483647`")  # noqa: E501
        if user_name is not None and len(user_name) < 1:
            raise ValueError("Invalid value for `user_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._user_name = user_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, XmlNs0AddUserRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
