# coding: utf-8

"""
    \"Data Governance Center: REST API v2\"

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class XmlNs0AddDomainTypesRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'names': 'str',
        'parent_domain_type_id': 'str'
    }

    attribute_map = {
        'names': 'names',
        'parent_domain_type_id': 'parentDomainTypeId'
    }

    def __init__(self, names=None, parent_domain_type_id=None):  # noqa: E501
        """XmlNs0AddDomainTypesRequest - a model defined in Swagger"""  # noqa: E501

        self._names = None
        self._parent_domain_type_id = None
        self.discriminator = None

        if names is not None:
            self.names = names
        if parent_domain_type_id is not None:
            self.parent_domain_type_id = parent_domain_type_id

    @property
    def names(self):
        """Gets the names of this XmlNs0AddDomainTypesRequest.  # noqa: E501

          # noqa: E501

        :return: The names of this XmlNs0AddDomainTypesRequest.  # noqa: E501
        :rtype: str
        """
        return self._names

    @names.setter
    def names(self, names):
        """Sets the names of this XmlNs0AddDomainTypesRequest.

          # noqa: E501

        :param names: The names of this XmlNs0AddDomainTypesRequest.  # noqa: E501
        :type: str
        """
        if names is not None and len(names) > 2147483647:
            raise ValueError("Invalid value for `names`, length must be less than or equal to `2147483647`")  # noqa: E501
        if names is not None and len(names) < 1:
            raise ValueError("Invalid value for `names`, length must be greater than or equal to `1`")  # noqa: E501

        self._names = names

    @property
    def parent_domain_type_id(self):
        """Gets the parent_domain_type_id of this XmlNs0AddDomainTypesRequest.  # noqa: E501

          # noqa: E501

        :return: The parent_domain_type_id of this XmlNs0AddDomainTypesRequest.  # noqa: E501
        :rtype: str
        """
        return self._parent_domain_type_id

    @parent_domain_type_id.setter
    def parent_domain_type_id(self, parent_domain_type_id):
        """Sets the parent_domain_type_id of this XmlNs0AddDomainTypesRequest.

          # noqa: E501

        :param parent_domain_type_id: The parent_domain_type_id of this XmlNs0AddDomainTypesRequest.  # noqa: E501
        :type: str
        """

        self._parent_domain_type_id = parent_domain_type_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, XmlNs0AddDomainTypesRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
