# coding: utf-8

"""
    \"Data Governance Center: REST API v2\"

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.xml_ns0_file_reference import XmlNs0FileReference  # noqa: F401,E501


class XmlNs0AddAttachmentRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'base_resource': 'object',
        'file': 'XmlNs0FileReference'
    }

    attribute_map = {
        'base_resource': 'baseResource',
        'file': 'file'
    }

    def __init__(self, base_resource=None, file=None):  # noqa: E501
        """XmlNs0AddAttachmentRequest - a model defined in Swagger"""  # noqa: E501

        self._base_resource = None
        self._file = None
        self.discriminator = None

        if base_resource is not None:
            self.base_resource = base_resource
        if file is not None:
            self.file = file

    @property
    def base_resource(self):
        """Gets the base_resource of this XmlNs0AddAttachmentRequest.  # noqa: E501

        The reference to the resource new attachment should be attached to  # noqa: E501

        :return: The base_resource of this XmlNs0AddAttachmentRequest.  # noqa: E501
        :rtype: object
        """
        return self._base_resource

    @base_resource.setter
    def base_resource(self, base_resource):
        """Sets the base_resource of this XmlNs0AddAttachmentRequest.

        The reference to the resource new attachment should be attached to  # noqa: E501

        :param base_resource: The base_resource of this XmlNs0AddAttachmentRequest.  # noqa: E501
        :type: object
        """

        self._base_resource = base_resource

    @property
    def file(self):
        """Gets the file of this XmlNs0AddAttachmentRequest.  # noqa: E501

        The reference to the file representing new attachment  # noqa: E501

        :return: The file of this XmlNs0AddAttachmentRequest.  # noqa: E501
        :rtype: XmlNs0FileReference
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this XmlNs0AddAttachmentRequest.

        The reference to the file representing new attachment  # noqa: E501

        :param file: The file of this XmlNs0AddAttachmentRequest.  # noqa: E501
        :type: XmlNs0FileReference
        """

        self._file = file

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, XmlNs0AddAttachmentRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
